#!/usr/bash
#
# Just a few certs generated by simple openssl commands and tiny openssl.conf
# This creates v1 certificates

cat <<EOF >nonUTF8.cnf
[ req ]
string_mask = nombstr
EOF

cat <<EOF >UTF8.cnf
[ req ]
string_mask = utf8only
EOF

[ -e "test.key" ] || openssl genrsa -out test.key 512
openssl req -x509 -config nonUTF8.cnf -new -nodes -key test.key -sha256 -days 5000 -set_serial 01 -out nonUTF8CA.crt -subj "/CN=This is the Issuer/CN=Lorem ipsum dolor sit amet,..."
openssl req -x509 -config UTF8.cnf -new -nodes -key test.key -sha256 -days 5000 -set_serial 01 -out UTF8CA.crt -subj "/CN=This is the Issuer/CN=Lorem ipsum dolor sit amet,..."

openssl req -new -nodes -config nonUTF8.cnf -out nonUTF8leadingSpaces.csr -key test.key -set_serial 02 -subj "/CN=                            Lots of leading spaces"
openssl req -new -nodes -config nonUTF8.cnf -out nonUTF8trailingSpaces.csr -key test.key -set_serial 02  -subj "/CN=Lots of trailing spaces                           "
openssl req -new -nodes -config nonUTF8.cnf -out nonUTF8spacesInMiddle.csr -key test.key -set_serial 02  -subj "/CN=Lots         of         spaces          in between"
openssl req -new -nodes -config nonUTF8.cnf -out nonUTF8weirdspaces.csr -key test.key -set_serial 02  -subj "/CN=Lots of weird spaces `echo -e 'Backspace\x08Htab\x09Newline\x0aVtab\x0bFfeed\x0cCR\x0d'`"

openssl req -new -nodes -config UTF8.cnf -out UTF8leadingSpaces.csr -key test.key -set_serial 02 -subj "/CN=                            Lots of leading spaces"
openssl req -new -nodes -config UTF8.cnf -out UTF8trailingSpaces.csr -key test.key -set_serial 02  -subj "/CN=Lots of trailing spaces                           "
openssl req -new -nodes -config UTF8.cnf -out UTF8spacesInMiddle.csr -key test.key -set_serial 02  -subj "/CN=Lots         of         spaces          in between"
openssl req -new -nodes -config UTF8.cnf -out UTF8weirdspaces.csr -key test.key -set_serial 02  -subj "/CN=Lots of weird spaces `echo -e 'Backspace\x08Htab\x09Newline\x0aVtab\x0bFfeed\x0cCR\x0d'`"

for a in leadingSpaces trailingSpaces spacesInMiddle weirdspaces
do
  openssl x509 -req -in nonUTF8$a.csr -CA nonUTF8CA.crt  -CAkey test.key -set_serial 02 -out nonUTF8$a.pem -days 4385 -sha256
  openssl x509 -req -in UTF8$a.csr -CA UTF8CA.crt  -CAkey test.key -set_serial 02 -out UTF8$a.pem -days 4385 -sha256
done
