name: Test It Works
on: [push, workflow_dispatch]
jobs:
  compare-to-openssl:
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Check certs in testCerts
        run: ./test.sh
